[2024-07-30T10:27:43.370+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T10:27:43.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-19T00:00:00+00:00 [queued]>
[2024-07-30T10:27:43.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-19T00:00:00+00:00 [queued]>
[2024-07-30T10:27:43.440+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T10:27:43.536+0000] {taskinstance.py:2330} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2018-11-19 00:00:00+00:00
[2024-07-30T10:27:43.557+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1232) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T10:27:43.561+0000] {standard_task_runner.py:63} INFO - Started process 1236 to run task
[2024-07-30T10:27:43.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipelinev5', 'Run_data_quality_checks', 'scheduled__2018-11-19T00:00:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpsi0h1rcn']
[2024-07-30T10:27:43.563+0000] {standard_task_runner.py:91} INFO - Job 218: Subtask Run_data_quality_checks
[2024-07-30T10:27:43.711+0000] {task_command.py:426} INFO - Running <TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-19T00:00:00+00:00 [running]> on host c3b60429ae20
[2024-07-30T10:27:44.039+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipelinev5' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2018-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-19T00:00:00+00:00'
[2024-07-30T10:27:44.040+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T10:27:44.059+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songplays table
[2024-07-30T10:27:44.073+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:44.092+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2024-07-30T10:27:44.097+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:44.100+0000] {data_quality_operator.py:30} INFO - Data quality on table songplays check passed with 4223 records
[2024-07-30T10:27:44.101+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for users table
[2024-07-30T10:27:44.114+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:44.132+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM users, parameters: None
[2024-07-30T10:27:44.136+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:44.138+0000] {data_quality_operator.py:30} INFO - Data quality on table users check passed with 86 records
[2024-07-30T10:27:44.139+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songs table
[2024-07-30T10:27:44.152+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:44.174+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songs, parameters: None
[2024-07-30T10:27:44.179+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:44.181+0000] {data_quality_operator.py:30} INFO - Data quality on table songs check passed with 71 records
[2024-07-30T10:27:44.183+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for artists table
[2024-07-30T10:27:44.203+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:44.233+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM artists, parameters: None
[2024-07-30T10:27:44.239+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:44.242+0000] {data_quality_operator.py:30} INFO - Data quality on table artists check passed with 69 records
[2024-07-30T10:27:44.243+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for times table
[2024-07-30T10:27:44.271+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:44.296+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM times, parameters: None
[2024-07-30T10:27:44.302+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:44.305+0000] {data_quality_operator.py:30} INFO - Data quality on table times check passed with 3899 records
[2024-07-30T10:27:44.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T10:27:44.328+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipelinev5, task_id=Run_data_quality_checks, run_id=scheduled__2018-11-19T00:00:00+00:00, execution_date=20181119T000000, start_date=20240730T102743, end_date=20240730T102744
[2024-07-30T10:27:44.384+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-30T10:27:44.416+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T10:27:44.444+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
