[2024-07-30T10:28:10.762+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T10:28:10.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-25T00:00:00+00:00 [queued]>
[2024-07-30T10:28:10.853+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-25T00:00:00+00:00 [queued]>
[2024-07-30T10:28:10.855+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T10:28:10.968+0000] {taskinstance.py:2330} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2018-11-25 00:00:00+00:00
[2024-07-30T10:28:10.982+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1338) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T10:28:10.985+0000] {standard_task_runner.py:63} INFO - Started process 1343 to run task
[2024-07-30T10:28:10.980+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipelinev5', 'Run_data_quality_checks', 'scheduled__2018-11-25T00:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpoq7_lw07']
[2024-07-30T10:28:10.986+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask Run_data_quality_checks
[2024-07-30T10:28:11.157+0000] {task_command.py:426} INFO - Running <TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-25T00:00:00+00:00 [running]> on host c3b60429ae20
[2024-07-30T10:28:11.530+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipelinev5' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2018-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-25T00:00:00+00:00'
[2024-07-30T10:28:11.535+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T10:28:11.589+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songplays table
[2024-07-30T10:28:11.626+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:11.674+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2024-07-30T10:28:11.692+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:11.706+0000] {data_quality_operator.py:30} INFO - Data quality on table songplays check passed with 5552 records
[2024-07-30T10:28:11.709+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for users table
[2024-07-30T10:28:11.739+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:11.796+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM users, parameters: None
[2024-07-30T10:28:11.821+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:11.826+0000] {data_quality_operator.py:30} INFO - Data quality on table users check passed with 91 records
[2024-07-30T10:28:11.828+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songs table
[2024-07-30T10:28:11.865+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:11.917+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songs, parameters: None
[2024-07-30T10:28:11.924+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:11.929+0000] {data_quality_operator.py:30} INFO - Data quality on table songs check passed with 71 records
[2024-07-30T10:28:11.931+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for artists table
[2024-07-30T10:28:11.964+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:12.028+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM artists, parameters: None
[2024-07-30T10:28:12.394+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:12.397+0000] {data_quality_operator.py:30} INFO - Data quality on table artists check passed with 69 records
[2024-07-30T10:28:12.399+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for times table
[2024-07-30T10:28:12.413+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:12.435+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM times, parameters: None
[2024-07-30T10:28:12.518+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:12.524+0000] {data_quality_operator.py:30} INFO - Data quality on table times check passed with 5548 records
[2024-07-30T10:28:12.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T10:28:12.577+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipelinev5, task_id=Run_data_quality_checks, run_id=scheduled__2018-11-25T00:00:00+00:00, execution_date=20181125T000000, start_date=20240730T102810, end_date=20240730T102812
[2024-07-30T10:28:12.774+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-30T10:28:12.873+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T10:28:12.901+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
