[2024-07-30T10:28:18.427+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T10:28:18.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-27T00:00:00+00:00 [queued]>
[2024-07-30T10:28:18.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-27T00:00:00+00:00 [queued]>
[2024-07-30T10:28:18.548+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T10:28:18.703+0000] {taskinstance.py:2330} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2018-11-27 00:00:00+00:00
[2024-07-30T10:28:18.718+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1380) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T10:28:18.720+0000] {standard_task_runner.py:63} INFO - Started process 1385 to run task
[2024-07-30T10:28:18.718+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipelinev5', 'Run_data_quality_checks', 'scheduled__2018-11-27T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpty_z2dks']
[2024-07-30T10:28:18.724+0000] {standard_task_runner.py:91} INFO - Job 282: Subtask Run_data_quality_checks
[2024-07-30T10:28:19.006+0000] {task_command.py:426} INFO - Running <TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-27T00:00:00+00:00 [running]> on host c3b60429ae20
[2024-07-30T10:28:19.387+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipelinev5' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2018-11-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-27T00:00:00+00:00'
[2024-07-30T10:28:19.391+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T10:28:19.433+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songplays table
[2024-07-30T10:28:19.469+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:19.505+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2024-07-30T10:28:19.514+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:19.519+0000] {data_quality_operator.py:30} INFO - Data quality on table songplays check passed with 6171 records
[2024-07-30T10:28:19.520+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for users table
[2024-07-30T10:28:19.544+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:19.583+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM users, parameters: None
[2024-07-30T10:28:19.590+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:19.593+0000] {data_quality_operator.py:30} INFO - Data quality on table users check passed with 95 records
[2024-07-30T10:28:19.594+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songs table
[2024-07-30T10:28:19.623+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:19.654+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songs, parameters: None
[2024-07-30T10:28:20.971+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:20.976+0000] {data_quality_operator.py:30} INFO - Data quality on table songs check passed with 71 records
[2024-07-30T10:28:20.984+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for artists table
[2024-07-30T10:28:21.012+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:21.088+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM artists, parameters: None
[2024-07-30T10:28:21.100+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:21.105+0000] {data_quality_operator.py:30} INFO - Data quality on table artists check passed with 69 records
[2024-07-30T10:28:21.107+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for times table
[2024-07-30T10:28:21.140+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:21.176+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM times, parameters: None
[2024-07-30T10:28:21.184+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:21.192+0000] {data_quality_operator.py:30} INFO - Data quality on table times check passed with 6483 records
[2024-07-30T10:28:21.199+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T10:28:21.235+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipelinev5, task_id=Run_data_quality_checks, run_id=scheduled__2018-11-27T00:00:00+00:00, execution_date=20181127T000000, start_date=20240730T102818, end_date=20240730T102821
[2024-07-30T10:28:21.358+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-30T10:28:21.449+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T10:28:21.491+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
