[2024-07-30T10:27:13.899+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T10:27:13.945+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-12T00:00:00+00:00 [queued]>
[2024-07-30T10:27:13.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-12T00:00:00+00:00 [queued]>
[2024-07-30T10:27:13.961+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T10:27:14.057+0000] {taskinstance.py:2330} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2018-11-12 00:00:00+00:00
[2024-07-30T10:27:14.085+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1105) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T10:27:14.084+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipelinev5', 'Run_data_quality_checks', 'scheduled__2018-11-12T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmppc7kw0wq']
[2024-07-30T10:27:14.092+0000] {standard_task_runner.py:91} INFO - Job 162: Subtask Run_data_quality_checks
[2024-07-30T10:27:14.091+0000] {standard_task_runner.py:63} INFO - Started process 1111 to run task
[2024-07-30T10:27:14.310+0000] {task_command.py:426} INFO - Running <TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-12T00:00:00+00:00 [running]> on host c3b60429ae20
[2024-07-30T10:27:14.672+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipelinev5' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2018-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-12T00:00:00+00:00'
[2024-07-30T10:27:14.675+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T10:27:14.699+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songplays table
[2024-07-30T10:27:14.730+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:14.780+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2024-07-30T10:27:14.800+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:14.810+0000] {data_quality_operator.py:30} INFO - Data quality on table songplays check passed with 2172 records
[2024-07-30T10:27:14.812+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for users table
[2024-07-30T10:27:14.862+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:14.952+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM users, parameters: None
[2024-07-30T10:27:14.968+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:14.973+0000] {data_quality_operator.py:30} INFO - Data quality on table users check passed with 78 records
[2024-07-30T10:27:14.974+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songs table
[2024-07-30T10:27:15.025+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:15.086+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songs, parameters: None
[2024-07-30T10:27:15.104+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:15.111+0000] {data_quality_operator.py:30} INFO - Data quality on table songs check passed with 71 records
[2024-07-30T10:27:15.113+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for artists table
[2024-07-30T10:27:15.161+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:15.217+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM artists, parameters: None
[2024-07-30T10:27:15.230+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:15.238+0000] {data_quality_operator.py:30} INFO - Data quality on table artists check passed with 69 records
[2024-07-30T10:27:15.240+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for times table
[2024-07-30T10:27:15.277+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:15.318+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM times, parameters: None
[2024-07-30T10:27:15.328+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:15.336+0000] {data_quality_operator.py:30} INFO - Data quality on table times check passed with 1833 records
[2024-07-30T10:27:15.337+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T10:27:15.377+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipelinev5, task_id=Run_data_quality_checks, run_id=scheduled__2018-11-12T00:00:00+00:00, execution_date=20181112T000000, start_date=20240730T102713, end_date=20240730T102715
[2024-07-30T10:27:15.557+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-30T10:27:15.683+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T10:27:15.803+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
