[2024-07-30T10:26:56.137+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T10:26:56.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-07T00:00:00+00:00 [queued]>
[2024-07-30T10:26:56.253+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-07T00:00:00+00:00 [queued]>
[2024-07-30T10:26:56.255+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T10:26:56.364+0000] {taskinstance.py:2330} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2018-11-07 00:00:00+00:00
[2024-07-30T10:26:56.379+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1023) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T10:26:56.382+0000] {standard_task_runner.py:63} INFO - Started process 1025 to run task
[2024-07-30T10:26:56.380+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipelinev5', 'Run_data_quality_checks', 'scheduled__2018-11-07T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpoaal24d9']
[2024-07-30T10:26:56.387+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask Run_data_quality_checks
[2024-07-30T10:26:56.604+0000] {task_command.py:426} INFO - Running <TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-07T00:00:00+00:00 [running]> on host c3b60429ae20
[2024-07-30T10:26:57.184+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipelinev5' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2018-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-07T00:00:00+00:00'
[2024-07-30T10:26:57.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T10:26:57.266+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songplays table
[2024-07-30T10:26:57.308+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:26:57.371+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2024-07-30T10:26:57.377+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:26:57.386+0000] {data_quality_operator.py:30} INFO - Data quality on table songplays check passed with 1255 records
[2024-07-30T10:26:57.387+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for users table
[2024-07-30T10:26:57.405+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:26:57.422+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM users, parameters: None
[2024-07-30T10:26:57.427+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:26:57.431+0000] {data_quality_operator.py:30} INFO - Data quality on table users check passed with 68 records
[2024-07-30T10:26:57.464+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songs table
[2024-07-30T10:26:57.488+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:26:57.516+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songs, parameters: None
[2024-07-30T10:26:58.082+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:26:58.089+0000] {data_quality_operator.py:30} INFO - Data quality on table songs check passed with 71 records
[2024-07-30T10:26:58.091+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for artists table
[2024-07-30T10:26:58.116+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:26:58.149+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM artists, parameters: None
[2024-07-30T10:26:58.202+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:26:58.205+0000] {data_quality_operator.py:30} INFO - Data quality on table artists check passed with 69 records
[2024-07-30T10:26:58.206+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for times table
[2024-07-30T10:26:58.235+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:26:58.268+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM times, parameters: None
[2024-07-30T10:26:58.274+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:26:58.277+0000] {data_quality_operator.py:30} INFO - Data quality on table times check passed with 1507 records
[2024-07-30T10:26:58.278+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T10:26:58.310+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipelinev5, task_id=Run_data_quality_checks, run_id=scheduled__2018-11-07T00:00:00+00:00, execution_date=20181107T000000, start_date=20240730T102656, end_date=20240730T102658
[2024-07-30T10:26:58.404+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-30T10:26:58.442+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T10:26:58.480+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
