[2024-07-30T10:27:36.526+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T10:27:36.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-17T00:00:00+00:00 [queued]>
[2024-07-30T10:27:36.603+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-17T00:00:00+00:00 [queued]>
[2024-07-30T10:27:36.604+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T10:27:36.810+0000] {taskinstance.py:2330} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2018-11-17 00:00:00+00:00
[2024-07-30T10:27:36.827+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1195) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T10:27:36.829+0000] {standard_task_runner.py:63} INFO - Started process 1198 to run task
[2024-07-30T10:27:36.827+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipelinev5', 'Run_data_quality_checks', 'scheduled__2018-11-17T00:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpwn0zs390']
[2024-07-30T10:27:36.831+0000] {standard_task_runner.py:91} INFO - Job 203: Subtask Run_data_quality_checks
[2024-07-30T10:27:37.062+0000] {task_command.py:426} INFO - Running <TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-17T00:00:00+00:00 [running]> on host c3b60429ae20
[2024-07-30T10:27:37.427+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipelinev5' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2018-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-17T00:00:00+00:00'
[2024-07-30T10:27:37.429+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T10:27:37.461+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songplays table
[2024-07-30T10:27:37.487+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:37.515+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2024-07-30T10:27:37.522+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:37.524+0000] {data_quality_operator.py:30} INFO - Data quality on table songplays check passed with 3625 records
[2024-07-30T10:27:37.525+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for users table
[2024-07-30T10:27:37.541+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:37.564+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM users, parameters: None
[2024-07-30T10:27:38.038+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:38.041+0000] {data_quality_operator.py:30} INFO - Data quality on table users check passed with 86 records
[2024-07-30T10:27:38.041+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songs table
[2024-07-30T10:27:38.056+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:38.077+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songs, parameters: None
[2024-07-30T10:27:38.087+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:38.090+0000] {data_quality_operator.py:30} INFO - Data quality on table songs check passed with 71 records
[2024-07-30T10:27:38.090+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for artists table
[2024-07-30T10:27:38.109+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:38.130+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM artists, parameters: None
[2024-07-30T10:27:38.137+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:38.141+0000] {data_quality_operator.py:30} INFO - Data quality on table artists check passed with 69 records
[2024-07-30T10:27:38.142+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for times table
[2024-07-30T10:27:38.165+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:27:38.187+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM times, parameters: None
[2024-07-30T10:27:38.193+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:27:38.196+0000] {data_quality_operator.py:30} INFO - Data quality on table times check passed with 3623 records
[2024-07-30T10:27:38.197+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T10:27:38.216+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipelinev5, task_id=Run_data_quality_checks, run_id=scheduled__2018-11-17T00:00:00+00:00, execution_date=20181117T000000, start_date=20240730T102736, end_date=20240730T102738
[2024-07-30T10:27:38.370+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-30T10:27:38.413+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T10:27:38.460+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
